export const tipoDeAccion = {
    AGREGAR_MASCOTA: 'AGREGAR_MASCOTA',
    ELIMINAR_MASCOTA: 'ELIMINAR_MASCOTA',
    MARCAR_ADOPTADA: 'MARCAR_ADOPTADA',
    MARCAR_DISPONIBLE: 'MARCAR_DISPONIBLE',
    EDITAR_MASCOTA: 'EDITAR_MASCOTA'

}